const mermaidArrays = {
  acceleration: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/acceleration_009.png`,
  ],
  attack: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/attack_009.png`,
  ],

  die: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/die_009.png`,
  ],

  hurt: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/hurt_009.png`,
  ],
  idle: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/idle_009.png`,
  ],
  joy: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/joy_009.png`,
  ],
  move: [
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_000.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_001.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_002.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_003.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_004.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_005.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_006.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_007.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_008.png`,
    `./img/mermaid/PNG/mermaid_${mermaidType}/move_009.png`,
  ],
};

const blowfishArrays = {
  attack: [
    './img/fish/PNG/blowfish/attack_000.png',
    './img/fish/PNG/blowfish/attack_001.png',
    './img/fish/PNG/blowfish/attack_002.png',
    './img/fish/PNG/blowfish/attack_003.png',
    './img/fish/PNG/blowfish/attack_004.png',
    './img/fish/PNG/blowfish/attack_005.png',
    './img/fish/PNG/blowfish/attack_006.png',
    './img/fish/PNG/blowfish/attack_007.png',
    './img/fish/PNG/blowfish/attack_008.png',
    './img/fish/PNG/blowfish/attack_009.png',
  ],

  die: [
    './img/fish/PNG/blowfish/die_000.png',
    './img/fish/PNG/blowfish/die_001.png',
    './img/fish/PNG/blowfish/die_002.png',
    './img/fish/PNG/blowfish/die_003.png',
    './img/fish/PNG/blowfish/die_004.png',
    './img/fish/PNG/blowfish/die_005.png',
    './img/fish/PNG/blowfish/die_006.png',
    './img/fish/PNG/blowfish/die_007.png',
    './img/fish/PNG/blowfish/die_008.png',
    './img/fish/PNG/blowfish/die_009.png',
  ],

  move: [
    './img/fish/PNG/blowfish/move_000.png',
    './img/fish/PNG/blowfish/move_001.png',
    './img/fish/PNG/blowfish/move_002.png',
    './img/fish/PNG/blowfish/move_003.png',
    './img/fish/PNG/blowfish/move_004.png',
    './img/fish/PNG/blowfish/move_005.png',
    './img/fish/PNG/blowfish/move_006.png',
    './img/fish/PNG/blowfish/move_007.png',
    './img/fish/PNG/blowfish/move_008.png',
    './img/fish/PNG/blowfish/move_009.png',
  ],
};

const redCrabArrays = {
  attack: [
    './img/fish/PNG/redCrab/attack_000.png',
    './img/fish/PNG/redCrab/attack_001.png',
    './img/fish/PNG/redCrab/attack_002.png',
    './img/fish/PNG/redCrab/attack_003.png',
    './img/fish/PNG/redCrab/attack_004.png',
    './img/fish/PNG/redCrab/attack_005.png',
    './img/fish/PNG/redCrab/attack_006.png',
    './img/fish/PNG/redCrab/attack_007.png',
    './img/fish/PNG/redCrab/attack_008.png',
    './img/fish/PNG/redCrab/attack_009.png',
  ],

  die: [
    './img/fish/PNG/redCrab/die_000.png',
    './img/fish/PNG/redCrab/die_001.png',
    './img/fish/PNG/redCrab/die_002.png',
    './img/fish/PNG/redCrab/die_003.png',
    './img/fish/PNG/redCrab/die_004.png',
    './img/fish/PNG/redCrab/die_005.png',
    './img/fish/PNG/redCrab/die_006.png',
    './img/fish/PNG/redCrab/die_007.png',
    './img/fish/PNG/redCrab/die_008.png',
    './img/fish/PNG/redCrab/die_009.png',
  ],

  idle: [
    './img/fish/PNG/redCrab/idle_000.png',
    './img/fish/PNG/redCrab/idle_001.png',
    './img/fish/PNG/redCrab/idle_002.png',
    './img/fish/PNG/redCrab/idle_003.png',
    './img/fish/PNG/redCrab/idle_004.png',
    './img/fish/PNG/redCrab/idle_005.png',
    './img/fish/PNG/redCrab/idle_006.png',
    './img/fish/PNG/redCrab/idle_007.png',
    './img/fish/PNG/redCrab/idle_008.png',
    './img/fish/PNG/redCrab/idle_009.png',
  ],
};

const yellowCrabArrays = {
  attack: [
    './img/fish/PNG/yellowCrab/attack_000.png',
    './img/fish/PNG/yellowCrab/attack_001.png',
    './img/fish/PNG/yellowCrab/attack_002.png',
    './img/fish/PNG/yellowCrab/attack_003.png',
    './img/fish/PNG/yellowCrab/attack_004.png',
    './img/fish/PNG/yellowCrab/attack_005.png',
    './img/fish/PNG/yellowCrab/attack_006.png',
    './img/fish/PNG/yellowCrab/attack_007.png',
    './img/fish/PNG/yellowCrab/attack_008.png',
    './img/fish/PNG/yellowCrab/attack_009.png',
  ],

  die: [
    './img/fish/PNG/yellowCrab/die_000.png',
    './img/fish/PNG/yellowCrab/die_001.png',
    './img/fish/PNG/yellowCrab/die_002.png',
    './img/fish/PNG/yellowCrab/die_003.png',
    './img/fish/PNG/yellowCrab/die_004.png',
    './img/fish/PNG/yellowCrab/die_005.png',
    './img/fish/PNG/yellowCrab/die_006.png',
    './img/fish/PNG/yellowCrab/die_007.png',
    './img/fish/PNG/yellowCrab/die_008.png',
    './img/fish/PNG/yellowCrab/die_009.png',
  ],

  move: [
    './img/fish/PNG/yellowCrab/move_000.png',
    './img/fish/PNG/yellowCrab/move_001.png',
    './img/fish/PNG/yellowCrab/move_002.png',
    './img/fish/PNG/yellowCrab/move_003.png',
    './img/fish/PNG/yellowCrab/move_004.png',
    './img/fish/PNG/yellowCrab/move_005.png',
    './img/fish/PNG/yellowCrab/move_006.png',
    './img/fish/PNG/yellowCrab/move_007.png',
    './img/fish/PNG/yellowCrab/move_008.png',
    './img/fish/PNG/yellowCrab/move_009.png',
  ],
};

const lionfishArrays = {
  attack: [
    './img/fish/PNG/lionfish/attack_000.png',
    './img/fish/PNG/lionfish/attack_001.png',
    './img/fish/PNG/lionfish/attack_002.png',
    './img/fish/PNG/lionfish/attack_003.png',
    './img/fish/PNG/lionfish/attack_004.png',
    './img/fish/PNG/lionfish/attack_005.png',
    './img/fish/PNG/lionfish/attack_006.png',
    './img/fish/PNG/lionfish/attack_007.png',
    './img/fish/PNG/lionfish/attack_008.png',
    './img/fish/PNG/lionfish/attack_009.png',
  ],

  die: [
    './img/fish/PNG/lionfish/die_000.png',
    './img/fish/PNG/lionfish/die_001.png',
    './img/fish/PNG/lionfish/die_002.png',
    './img/fish/PNG/lionfish/die_003.png',
    './img/fish/PNG/lionfish/die_004.png',
    './img/fish/PNG/lionfish/die_005.png',
    './img/fish/PNG/lionfish/die_006.png',
    './img/fish/PNG/lionfish/die_007.png',
    './img/fish/PNG/lionfish/die_008.png',
    './img/fish/PNG/lionfish/die_009.png',
   
  ],

  move: [
    './img/fish/PNG/lionfish/move_000.png',
    './img/fish/PNG/lionfish/move_001.png',
    './img/fish/PNG/lionfish/move_002.png',
    './img/fish/PNG/lionfish/move_003.png',
    './img/fish/PNG/lionfish/move_004.png',
    './img/fish/PNG/lionfish/move_005.png',
    './img/fish/PNG/lionfish/move_006.png',
    './img/fish/PNG/lionfish/move_007.png',
    './img/fish/PNG/lionfish/move_008.png',
    './img/fish/PNG/lionfish/move_009.png',
  ]
}

const hammerheadArrays = {
  attack: [
    './img/fish/PNG/hammerhead/attack_000.png',
    './img/fish/PNG/hammerhead/attack_001.png',
    './img/fish/PNG/hammerhead/attack_002.png',
    './img/fish/PNG/hammerhead/attack_003.png',
    './img/fish/PNG/hammerhead/attack_004.png',
    './img/fish/PNG/hammerhead/attack_005.png',
    './img/fish/PNG/hammerhead/attack_006.png',
    './img/fish/PNG/hammerhead/attack_007.png',
    './img/fish/PNG/hammerhead/attack_008.png',
    './img/fish/PNG/hammerhead/attack_009.png',
  ],

  die: [
    './img/fish/PNG/hammerhead/die_000.png',
    './img/fish/PNG/hammerhead/die_001.png',
    './img/fish/PNG/hammerhead/die_002.png',
    './img/fish/PNG/hammerhead/die_003.png',
    './img/fish/PNG/hammerhead/die_004.png',
    './img/fish/PNG/hammerhead/die_005.png',
    './img/fish/PNG/hammerhead/die_006.png',
    './img/fish/PNG/hammerhead/die_007.png',
    './img/fish/PNG/hammerhead/die_008.png',
    './img/fish/PNG/hammerhead/die_009.png',
  ],

  move: [
    './img/fish/PNG/hammerhead/move_000.png',
    './img/fish/PNG/hammerhead/move_001.png',
    './img/fish/PNG/hammerhead/move_002.png',
    './img/fish/PNG/hammerhead/move_003.png',
    './img/fish/PNG/hammerhead/move_004.png',
    './img/fish/PNG/hammerhead/move_005.png',
    './img/fish/PNG/hammerhead/move_006.png',
    './img/fish/PNG/hammerhead/move_007.png',
    './img/fish/PNG/hammerhead/move_008.png',
    './img/fish/PNG/hammerhead/move_009.png',
  ],
};

const sharkArrays = {
  attack: [
    './img/fish/PNG/shark/attack_000.png',
    './img/fish/PNG/shark/attack_001.png',
    './img/fish/PNG/shark/attack_002.png',
    './img/fish/PNG/shark/attack_003.png',
    './img/fish/PNG/shark/attack_004.png',
    './img/fish/PNG/shark/attack_005.png',
    './img/fish/PNG/shark/attack_006.png',
    './img/fish/PNG/shark/attack_007.png',
    './img/fish/PNG/shark/attack_008.png',
    './img/fish/PNG/shark/attack_009.png',

  ],

  die: [
    './img/fish/PNG/shark/die_000.png',
    './img/fish/PNG/shark/die_001.png',
    './img/fish/PNG/shark/die_002.png',
    './img/fish/PNG/shark/die_003.png',
    './img/fish/PNG/shark/die_004.png',
    './img/fish/PNG/shark/die_005.png',
    './img/fish/PNG/shark/die_006.png',
    './img/fish/PNG/shark/die_007.png',
    './img/fish/PNG/shark/die_008.png',
    './img/fish/PNG/shark/die_009.png',
  ],
  
  move: [
    './img/fish/PNG/shark/move_000.png',
    './img/fish/PNG/shark/move_001.png',
    './img/fish/PNG/shark/move_002.png',
    './img/fish/PNG/shark/move_003.png',
    './img/fish/PNG/shark/move_004.png',
    './img/fish/PNG/shark/move_005.png',
    './img/fish/PNG/shark/move_006.png',
    './img/fish/PNG/shark/move_007.png',
    './img/fish/PNG/shark/move_008.png',
    './img/fish/PNG/shark/move_009.png',
  ],
};
